apiVersion: v1
entries:
  teamcity:
  - apiVersion: v2
    appVersion: 2020.1.4
    created: "2020-10-08T09:43:45.526814-05:00"
    description: A Helm chart to install a simple TeamCity installation
    digest: 7674bc694aa05007104542ae2865d2e5546a07467ca5bf1355a42107d650def0
    icon: https://cdn.freebiesupply.com/logos/large/2x/teamcity-icon-logo-svg-vector.svg
    maintainers:
    - email: seppler@presidio.com
      name: Scott Eppler
      url: https://github.com/audioboxer217/
    name: teamcity
    sources:
    - https://github.com/codaglobal/teamcity_helm
    type: application
    urls:
    - https://codaglobal.github.io/coda-charts/teamcity-0.1.0.tgz
    version: 0.1.0
generated: "2020-10-08T09:43:45.51985-05:00"
